### ISSUE TITLE
Support for Keycloak 24

### ISSUE THREAD

**Issue by jbostoen** [mesutpiskin/keycloak-2fa-email-authenticator#33]
Any support planned for Keycloak 24, please?

**Comment by Barabek88** [comment]
Do you have any problem with Keycloak 24?

I compiled the jar from the sources and connected it to Keycloak 24.0.1 quietly. Everything is working.

**Comment by Axent96** [comment]
@Barabek88 do you can please provide your jar file?

**Comment by MultiAlator** [comment]
It is not working for me on Keycloak version 24.0.3.

I get the following error:
`2024-04-22T09:12:35.229025495Z 2024-04-22 09:12:35,227 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-8) Uncaught server error: java.lang.NoSuchMethodError: 'javax.ws.rs.core.Response org.keycloak.forms.login.LoginFormsProvider.createForm(java.lang.String)'
2024-04-22T09:12:35.229053606Z 	at com.mesutpiskin.keycloak.auth.email.EmailAuthenticatorForm.challenge(EmailAuthenticatorForm.java:52)
2024-04-22T09:12:35.229056943Z 	at com.mesutpiskin.keycloak.auth.email.EmailAuthenticatorForm.authenticate(EmailAuthenticatorForm.java:40)
2024-04-22T09:12:35.229059730Z 	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:442)
2024-04-22T09:12:35.229061994Z 	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
2024-04-22T09:12:35.229064206Z 	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:377)
2024-04-22T09:12:35.229066780Z 	at org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:178)
2024-04-22T09:12:35.229069084Z 	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:154)
2024-04-22T09:12:35.229071191Z 	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1011)
2024-04-22T09:12:35.229073465Z 	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:365)
2024-04-22T09:12:35.229085212Z 	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:336)
2024-04-22T09:12:35.229087452Z 	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:328)
2024-04-22T09:12:35.229089344Z 	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:393)
2024-04-22T09:12:35.229091273Z 	at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
2024-04-22T09:12:35.229093241Z 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
2024-04-22T09:12:35.229095197Z 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
2024-04-22T09:12:35.229098223Z 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
2024-04-22T09:12:35.229100387Z 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
2024-04-22T09:12:35.229102304Z 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
2024-04-22T09:12:35.229104323Z 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
2024-04-22T09:12:35.229106310Z 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
2024-04-22T09:12:35.229110798Z 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
2024-04-22T09:12:35.229112714Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-04-22T09:12:35.229114636Z 	at java.base/java.lang.Thread.run(Thread.java:840)`

How can i solve this problem?
