### ISSUE TITLE
Support for 25.0.2

### ISSUE THREAD

**Issue by daniel-tedra** [mesutpiskin/keycloak-2fa-email-authenticator#45]
Everything seems to work but the last step where the plugin must show the OTP form.

`[org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-836) Uncaught server error: java.lang.NoSuchMethodError: 'javax.ws.rs.core.Response org.keycloak.forms.login.LoginFormsProvider.createForm(java.lang.String)'
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at com.mesutpiskin.keycloak.auth.email.EmailAuthenticatorForm.challenge(EmailAuthenticatorForm.java:52)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at com.mesutpiskin.keycloak.auth.email.EmailAuthenticatorForm.authenticate(EmailAuthenticatorForm.java:40)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:442)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:377)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:246)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:377)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:178)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:154)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1031)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:376)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:347)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:339)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:405)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_13d428b70e62601585246c086a52f40868a3208e.invoke(Unknown Source)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
ago 13 10:20:36 dc1-keycloak01.tedra.es kc.sh[1158537]:         at java.base/java.lang.Thread.run(Thread.java:840)`

**Comment by daniel-tedra** [comment]
It seems from KC22 **_javax.ws.rs.core.*_** is no longer allowed.

https://www.keycloak.org/2023/07/keycloak-2200-released.html#Context%20and%20dependency%20injection%20no%20longer%20enabled%20to%20JAX-RS%20Resources

**Comment by daniel-tedra** [comment]
Hi I'm not a developer and I don't have a developer environment set to build, I just wanted a pre-built binary version with support for KC 25.02.

**Comment by mesutpiskin** [comment]
KC 25 support codes merged

**Comment by kominoshja** [comment]
@mesutpiskin I've verified the latest code builds correctly, but you might want to release a new package so folks don't download the wrong version

**Comment by kominoshja** [comment]
Not really, in my case, i had pulled the code, installed jdk17 and maven, and simply ran mvn package

**Comment by leobury** [comment]
Ok that's why, i'm with jdk23...

**Comment by dedo1911** [comment]
> KC 25 support codes merged

Thanks! Are you able to provide up to date build on Github Releases?

**Comment by henri9813** [comment]
Hello,

Can you create a new release ?

Thanks
